version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ANALYZER_MODE=auto
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=mistralai/mistral-7b-instruct:free
    volumes:
      - ./backend:/app
      - ./backend/storage:/app/storage
    depends_on:
      - frontend
