services:
  - type: web
    name: resumatch-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    buildCommand: echo "Docker build handled by Render"
    plan: free
    healthCheckPath: /health
    # Auto deploy only on main branch
    branch: main
    # Reduce build timeout
    buildFilter:
      paths:
      - backend/**
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
        # Note: Set this value directly in the Render dashboard
        # Do not include the "Bearer " prefix in the API key
      - key: OPENROUTER_MODEL
        value: mistralai/mistral-7b-instruct:free
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1 