services:
  - type: web
    name: resumatch-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: echo "Docker build handled by Render"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
        # Note: Set this value directly in the Render dashboard
        # Do not include the "Bearer " prefix in the API key
      - key: OPENROUTER_MODEL
        value: mistralai/mistral-7b-instruct:free
      - key: PORT
        value: 8000 